### ISSUE TITLE
create a stub from a9n

### ISSUE THREAD

**Issue by oshanz** [knapo/a9n#14]
```
A9n.stub_any_instance :app_host, 'http://example.com' do
      ## code
end
```

this is what I want to so. but output is

`A9n::NoSuchConfigurationVariableError: stub_any_instance
`

what is the solution for that? all my other stubs works fine.

**Comment by knapo** [comment]
Hey @oshanz!

Note that `A9n` is a `Module` and `stub_any_instance` is designed to stub instances of given class, not given class or module.

You should either use just `stub` or `A9n.set(:app_host, 'http://example.com')`, which was introduced in `0.8.0`.

I haven't used `minitest` for ages, but believe that something like `A9n.stub(:app_host, 'http://example.com')` should work.

Hope that helps.
